#!/bin/bash

ROOT_DIR=$PWD
INSTALLER_DIR=$ROOT_DIR/.installer/darwin
CACHE_DIR=$INSTALLER_DIR/cache
OUTPUT_DIR=$INSTALLER_DIR/output
ASSETS_DIR=$INSTALLER_DIR/assets

mkdir -p $CACHE_DIR

if [ "$KEY_PASSWORD" == "" ]; then
  echo "KEY_PASSWORD is blank"
  exit 1
fi

if [ ! -f $CACHE_DIR/node.pkg ]; then
  pushd $CACHE_DIR
  curl -sO https://s3-us-west-2.amazonaws.com/gateblu/node-binaries/darwin/node.pkg
  popd
fi

if [ ! -f $CACHE_DIR/npm.pkg ]; then
  pushd $CACHE_DIR
  curl -sO https://s3-us-west-2.amazonaws.com/gateblu/node-binaries/darwin/npm.pkg
  popd
fi

rm -rf $CACHE_DIR/dmg
mkdir -p $CACHE_DIR/dmg

sudo rm -rf $OUTPUT_DIR
rsync -avq --exclude='node_modules' --exclude='meshblu.json' --exclude='test' --exclude='.git' --exclude='.installer' $ROOT_DIR/ $OUTPUT_DIR
cp $INSTALLER_DIR/com.octoblu.GatebluService.plist $INSTALLER_DIR/start-gateblu-service $OUTPUT_DIR
pushd $OUTPUT_DIR
npm install -s --production
sudo chown -R root:wheel $OUTPUT_DIR

identity="A5D9EE988CEFE25C6D04679D00F9C8C60B63C240"
identity_name="Developer ID Installer: Octoblu Inc. (JLSZ8Q5945)"

pkgbuild --root . \
  --identifier com.octoblu.GatebluService \
  --version 1.0 \
  --component-plist $INSTALLER_DIR/GatebluServiceCore.plist \
  --ownership recommended \
  --install-location "/Library/Octoblu/GatebluService" \
  --scripts $INSTALLER_DIR/Scripts \
  $CACHE_DIR/GatebluServiceCore.pkg

echo "### create keychain"
security create-keychain -p travis mac-build.keychain
security import $INSTALLER_DIR/certs/apple.cer -k ~/Library/Keychains/mac-build.keychain -T /usr/bin/codesign
security import $INSTALLER_DIR/certs/dist.p12 -k ~/Library/Keychains/mac-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
security import $INSTALLER_DIR/certs/installer.p12 -k ~/Library/Keychains/mac-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign -T /usr/bin/productbuild
echo "### signing package"

codesign --force --verify --verbose --keychain ~/Library/Keychains/mac-build.keychain --sign "$identity" "$CACHE_DIR/GatebluServiceCore.pkg"
codesign --force --verify --verbose --keychain ~/Library/Keychains/mac-build.keychain --sign "$identity" "$CACHE_DIR/GatebluService.pkg"

echo "### building installer"

productbuild --distribution $INSTALLER_DIR/distribution.plist \
  --resources $INSTALLER_DIR  \
  --package-path $CACHE_DIR \
  --keychain ~/Library/Keychains/mac-build.keychain \
  --sign "$identity_name" \
  $CACHE_DIR/GatebluService.pkg

cp $CACHE_DIR/GatebluService.pkg $CACHE_DIR/dmg

echo "### verifying signature"
codesign -vvv -d "$CACHE_DIR/GatebluServiceCore.pkg"
codesign -vvv -d "$CACHE_DIR/GatebluService.pkg"
# sudo spctl -a -vvvv "$PLATFORM_APP_DIR"

echo "### building dmg"
umount /Volumes/GatebluService > /dev/null 2>&1

pushd $CACHE_DIR
$INSTALLER_DIR/create-dmg --volname GatebluService \
  --volicon $ASSETS_DIR/gateblu-disk-image.icns \
  --background $ASSETS_DIR/background.png \
  --window-size 512 320 \
  --icon-size 128 \
  --icon GatebluService.pkg 256 200 \
  --hide-extension GatebluService.pkg \
  $CACHE_DIR/GatebluService.dmg \
  $CACHE_DIR/dmg

echo "### remove keychain"
security delete-keychain mac-build.keychain

popd
