#!/bin/sh

export GATEBLU_HOME="$HOME/Library/Octoblu/GatebluService"
export MESHBLU_JSON_FILE=$GATEBLU_HOME/meshblu.json
export GATEBLU_DEVICE_PATH=$GATEBLU_HOME/devices
export GATEBLU_TMP_PATH=$GATEBLU_HOME/tmp
export DEBUG=gateblu*
node/bin/node command.js
